name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Verificação de Código
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpstan, phpcs
          coverage: pcov

      - name: Instalar dependências do Composer
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Executar PHPStan (Análise Estática)
        run: vendor/bin/phpstan analyse

      - name: Executar PHP_CodeSniffer (Verificação de Padrões)
        run: vendor/bin/phpcs

  build:
    name: Build dos Containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker e Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Iniciar Docker Compose
        run: docker-compose up -d

  test:
    name: Execução dos Testes
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: pcov

      - name: Instalar dependências do Composer
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Executar Migrations
        run: docker-compose exec app php artisan migrate --force

      - name: Executar Testes
        run: docker-compose exec app php artisan test --coverage

      - name: Upload Relatório de Cobertura
        uses: codecov/codecov-action@v3
        with:
          file: tests/coverage/clover.xml